(defun recker/build-capture-templates ()
  (let* ((org org-directory)
         (opsat (list 'file (concat org "/opsat.org")))
         (work (list 'file (concat org "/work.org.gpg")))
         (therapy `(file+olp+datetree ,(concat org "/therapy.org.gpg")))
         (blog (list 'file (expand-file-name (format-time-string "~/src/blog/entries/%Y-%m-%d.html"))))
         (blog-meta (format-time-string "<!-- meta:title -->\n<!-- meta:banner %Y-%m-%d.jpg -->\n\n")))
    `(("o" "Task" entry ,opsat "* TODO %?\n" :empty-lines 1)
      ("w" "Work Task" entry ,work "* TODO %?\n" :empty-lines 1)
      ("b" "Blog Entry" plain ,blog ,blog-meta)
      ("m" "Therapy Check-in" plain ,therapy)
      ("n" "Meeting Notes" entry ,work "* %?\n" :empty-lines 1 :jump-to-captured t))))

(setq org-capture-templates (recker/build-capture-templates))
(global-set-key (kbd "C-c c") 'org-capture)
