(source gnu)
(source melpa)

(depends-on "company")
(depends-on "darktooth-theme")
(depends-on "elpy")
(depends-on "emmet-mode")
(depends-on "git-gutter")
(depends-on "gruvbox-theme")
(depends-on "helm")
(depends-on "helm-projectile")
(depends-on "helm-swoop")
(depends-on "js2-mode")
(depends-on "magit")
(depends-on "projectile")
(depends-on "web-mode")
(depends-on "whitespace-cleanup-mode")
(depends-on "yaml-mode")
