#+TITLE: Emacs Configuration (old)
#+AUTHOR: Alex Recker
#+OPTIONS: num:nil
#+STARTUP: showall
#+PROPERTY: header-args :results none

This is the old config that I'm slowly incorporating into the new
version.

#+begin_src emacs-lisp
  (defun recker/path (dir &optional subpath)
    "Build a path name relative to the home directory."
    (let ((dir (file-name-as-directory (cl-getf recker/path-aliases dir (format "~/%s" dir))))
          (subpath (or subpath "")))
      (concat dir subpath)))
#+end_src

You can set your own aliases by overriding or appending
=recker/paths-aliases=.

#+begin_src emacs-lisp
  (setq recker/path-aliases
        '(:home "~"
          :desktop "~/desktop"
          :docs "~/docs"
          :pics "~/pics"
          :public "~/public"
          :src "~/src"
          :emacs "~/.emacs.d"))
#+end_src

Or it might look like this on a mac.

#+begin_src emacs-lisp
  (if (string-equal system-type "darwin")
      (setq recker/path-aliases
            '(:home "~"
              :desktop "~/Desktop"
              :docs "~/Documents"
              :pics "~/Pictures"
              :public "~/Public"
              :src "~/src"
              :emacs "~/.emacs.d")))
#+end_src

* Passwords

I use the =pass= tool for personal secret management.  It's my own
crummy implementation.

#+begin_src emacs-lisp
(defun recker/pass-directory ()
  (or (bound-and-true-p recker/active-pass-directory)
      (expand-file-name "~/.password-store")))

(defun recker/pass--file-to-entry (path)
  (file-name-sans-extension
   (file-relative-name path (recker/pass-directory))))

(defun recker/pass-list-entries ()
  (mapcar
   #'recker/pass--file-to-entry
   (directory-files-recursively (recker/pass-directory) ".gpg")))

(defun recker/pass-to-string (path)
  (cl-first
   (split-string
    (shell-command-to-string
     (format "PASSWORD_STORE_DIR=\"%s\" pass \"%s\" | head -1" (recker/pass-directory) path))
    "\n")))

(defun recker/pass-to-clip (path)
  (interactive (list (completing-read "Password: " (recker/pass-list-entries) nil t)))
  (shell-command
   (format "PASSWORD_STORE_DIR=\"%s\" pass -c \"%s\"" (recker/pass-directory) path)))

(defun recker/pass-to-clip-work ()
  (interactive)
  (let ((recker/active-pass-directory (expand-file-name "~/.password-store-work")))
    (funcall-interactively #'recker/pass-to-clip (completing-read "Password: " (recker/pass-list-entries) nil t))))

(global-set-key (kbd "C-x p") 'recker/pass-to-clip)
(global-set-key (kbd "C-x w") 'recker/pass-to-clip-work)
#+end_src

* Org

Make sure =org-tempo= is loaded so shortcuts work for code blocks, I
guess.  This is a recent workaround.

#+begin_src emacs-lisp
(require 'org-tempo)
#+end_src

Run **code blocks** interactively without the confirmation prompt each
time.  Set up some languages.

#+begin_src emacs-lisp
  (setq org-confirm-babel-evaluate nil)
  (org-babel-do-load-languages
   'org-babel-load-languages
   '((java . t)
     (perl . t)
     (python . t)
     (ruby . t)
     (shell . t)))
#+end_src

Use MY OWN FUNCTION for searching org notes.

#+begin_src emacs-lisp
(defun recker/opsat-find ()
  (interactive)
  (let ((files
         (mapcar #'file-name-nondirectory (directory-files-recursively (recker/path :docs) "\\.org$" nil nil t))))
    (find-file (recker/path :docs (ido-completing-read "File: " files nil nil)))))

(global-set-key (kbd "C-c o") 'recker/opsat-find)
#+end_src

Don't mess with indentation or empty lines.

#+begin_src emacs-lisp
  (setq org-adapt-indentation nil)
  (setq org-cycle-separator-lines -1)
#+end_src

Fix yasnippet in org mode.

#+begin_src emacs-lisp
  (defun recker/fix-yas-in-org ()
    (setq-local yas-buffer-local-condition
                '(not (org-in-src-block-p t))))
  (add-hook 'org-mode-hook #'recker/fix-yas-in-org)
#+end_src

[[https://plantuml.com/emacs][Plantuml]] integration.  Make sure you download the [[https://plantuml.com/download][JAR file]] and save it
to =~/.plantuml/plantuml.jar=.

#+begin_src emacs-lisp
  (use-package plantuml-mode
    :ensure t
    :config (setq org-plantuml-jar-path (recker/path :home ".plantuml/plantuml.jar"))
    :init
    (add-to-list 'org-src-lang-modes '("plantuml" . plantuml))
    (org-babel-do-load-languages 'org-babel-load-languages '((plantuml . t))))
#+end_src

Re-render images after executing code blocks.

#+begin_src emacs-lisp
  (defun recker/org-rerender-images ()
    (when org-inline-image-overlays
      (org-redisplay-inline-images)))

  (add-hook 'org-babel-after-execute-hook #'recker/org-rerender-images)
#+end_src

Configure **capture templates** and map the selector to =C-c c=.

#+begin_src emacs-lisp
  (setq org-capture-templates '())
  (global-set-key (kbd "C-c c") 'org-capture)

  (add-to-list 'org-capture-templates
               `("j" "journal entry" plain (file+olp+datetree ,(recker/path :docs "journal.org")) "%?\n"
                 :empty-lines-before 1 :empty-lines-after 1))

  (add-to-list 'org-capture-templates
               `("m" "mixtape notes" plain (file+olp+datetree ,(recker/path :docs "mixtape.org")) "%?\n"
                 :empty-lines-before 1 :empty-lines-after 1))

  (add-to-list 'org-capture-templates
               `("i" "idea" plain (file+olp+datetree ,(recker/path :docs "ideas.org")) "%?\n"
                 :empty-lines-before 1 :empty-lines-after 1))

  (add-to-list 'org-capture-templates
               `("p" "productivity task" entry (file+headline ,(recker/path :docs "opsat.org") "Productivity") "* TODO %?\n"))

  (add-to-list 'org-capture-templates
               `("w" "work task" entry (file ,(recker/path :docs "work.org")) "* TODO %?\n"))
#+end_src

Configure **agenda** and set up and map the view to =C-c a=.

#+begin_src emacs-lisp
(setq org-agenda-files (list (recker/path :docs)))
(setq org-directory (list (recker/path :docs)))
(setq org-agenda-start-with-follow-mode t)
(global-set-key (kbd "C-c a") 'org-agenda)
(setq org-agenda-tag-filter-preset '("-ARCHIVE"))
#+end_src

Configure **attachments**.

#+begin_src emacs-lisp
(setq org-attach-directory (recker/path :docs "attachments/"))
(setq org-attach-archive-delete 't)
#+end_src

Configure **publish projects**.

#+begin_src emacs-lisp
(setq org-publish-project-alist '())
#+end_src

Install htmlize for sweet snyntax highlighting on HTML exports.

#+begin_src emacs-lisp
(use-package htmlize :ensure t)
#+end_src

Open up a new blog post.

#+begin_src emacs-lisp
  (defun recker/today ()
    "Open today's journal entry."
    (interactive)
    (let* ((target
            (recker/path :src (format-time-string "blog/_posts/%Y-%m-%d-entry.md")))
           (frontmatter
            (format-time-string "---\ntitle:\nbanner: %Y-%m-%d.jpg\n---\n\n")))
      (if (file-exists-p target)
          (find-file target)
        (progn (find-file target)
               (insert frontmatter)))))
  (global-set-key (kbd "C-c t") 'recker/today)
#+end_src

Don't show archived or done items in the agenda.

#+begin_src emacs-lisp
  (setq org-agenda-skip-scheduled-if-done t
        org-agenda-skip-deadline-if-done  t
        org-agenda-archives-mode nil)
#+end_src

Don't automatically search in =org-goto=.

#+begin_src emacs-lisp
  (setq org-goto-auto-isearch nil)
#+end_src

* Functions

Some other helpful functions.

#+begin_src emacs-lisp
  (defun recker/docs-sync ()
    (interactive)
    (let ((command (format "git-sync -d %s" (recker/path :docs))))
      (call-process-shell-command command nil "*docs-sync*" t))
    (message "docs-sync: successful"))
  (global-set-key (kbd "C-c d") 'recker/docs-sync)
#+end_src
