(global-set-key (kbd "C-c l") 'sort-lines)
(global-set-key (kbd "C-c r") 'replace-string)
(global-set-key (kbd "C-x P") 'recker/purge-buffers)
(global-set-key (kbd "C-x k") 'kill-this-buffer)
(global-set-key (kbd "C-x r b") 'recker/ido-bookmark-jump)
(global-set-key (kbd "C-x t") 'recker/ansi-term)
(global-set-key (kbd "C-c t") 'recker/today)
(global-set-key (kbd "C-c o") 'recker/opsat-find)
(global-set-key (kbd "C-c c") 'org-capture)
(global-set-key (kbd "C-c a") 'org-agenda)
