#!/usr/bin/env python
import pathlib
import logging
import sys

logging.basicConfig(format='clean: %(message)s', level=logging.INFO, stream=sys.stderr)


def main():
    here = pathlib.Path('.')
    for pattern in read_gitignore():
        results = here.glob(pattern)
        files = [r for r in results if r.is_file() or r.is_symlink()]
        dirs = [r for r in results if r.is_dir()]
        for item in files:
            item.unlink()
        for item in dirs:
            item.rmdir()


def read_gitignore():
    with pathlib.Path('./.gitignore').open('r') as f:
        for line in f.readlines():
            line = line.strip()
            if line:
                yield line


if __name__ == '__main__':
    main()
